import "ActorProperty.idl";
namespace EngineInterface_WRC
{    
    runtimeclass ActorComponent : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {                
        ActorComponent(String name);
        String Name;        
        Windows.Foundation.Collections.IObservableVector<ActorProperty> Properties{ get; };        
    }
}