#pragma once
#include "EngineCore_WRC.EngineCore.g.h"
#include <concurren>

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.

namespace Engine
{
    class EngineCore;
}

namespace winrt::EngineCore_WRC::implementation
{
    struct EngineCore : EngineCoreT<EngineCore>
    {
        EngineCore();

        void Initialize(winrt::Microsoft::UI::Xaml::Controls::SwapChainPanel const& panel);
        void UnInitialize();
        void Tick();
        void StartRenderLoop();
        void StopRenderLoop();
        void ProcessInput();
        void OnActivated();
        void OnDeactivated();
        void OnSuspending();
        void OnResuming();
        void OnWindowSizeChanged(float width, float height);
        void OnSwapchainXamlChanged(double rasterizationScale, winrt::Windows::Foundation::Size const& size, float compositonScaleX, float compositonScaleY);
        void OnOrientationChanged(winrt::Windows::Graphics::Display::DisplayOrientations const& orientation);
        void ValidateDevice();
        winrt::EngineCore_WRC::EngineCriticalSection GetCriticalSection();
        void GetDefaultSize(float& width, float& height) noexcept;
        void LoadScriptProject(hstring const& path);
    private:
        std::unique_ptr<Engine::EngineCore> EngineCoreNative;
        concurrency::critical_section m_criticalSection;
    };
}
namespace winrt::EngineCore_WRC::factory_implementation
{
    struct EngineCore : EngineCoreT<EngineCore, implementation::EngineCore>
    {
    };
}
