namespace EngineInterface_WRC
{
	runtimeclass ComponentPropertyProxy : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
	{
		ComponentPropertyProxy(String name);
		String Name{ get; };
		Microsoft.UI.Xaml.UIElement MappedControl;
	}

	runtimeclass ActorComponentProxy
	{
		ActorComponentProxy(String name);
		String Name{ get; };
		Windows.Foundation.Collections.IObservableVector<ActorComponentProxy> ChildComponents{ get; };
		Windows.Foundation.Collections.IObservableVector<ComponentPropertyProxy> Properties{ get; };
	}

	runtimeclass ActorProxy
	{
		ActorProxy(String name, String type);
		String Name;
		String Type;
		Windows.Foundation.Collections.IObservableVector<ActorProxy> ChildActors{ get; };
		Windows.Foundation.Collections.IObservableVector<ActorComponentProxy> Components{ get; };
	}

}
