namespace EngineInterface_WRC
{
	[default_interface]
	runtimeclass ComponentPropertyProxy
	{
		String Name{get; };
		ComponentPropertyProxy();
		String Value;
	}


	[default_interface]
	runtimeclass ActorComponentProxy
	{
		String Name{get; };
		ActorComponentProxy();
		Windows.Foundation.Collections.IVector<ComponentPropertyProxy> Properties{get; };
	}

	[default_interface]
	runtimeclass ActorProxy
	{
		String Name;
		ActorProxy();
		Windows.Foundation.Collections.IVector<ActorComponentProxy> Components{ get; };
	}

}
