#pragma once

import "ActorProperty.idl";
namespace AuthoringTool
{    
    runtimeclass ActorComponent
    {                
        ActorComponent(String name);
        String Name{ get; };
        Windows.Foundation.Collections.IObservableVector<ActorProperty> Properties{ get; };        
    }
}