#pragma once

namespace AuthoringTool
{
    [default_interface]
    runtimeclass ActorProperty : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {        
        ActorProperty(String name);
        String Name;        
    }        
}

