#pragma once

import "ActorComponent.idl";

namespace AuthoringTool
{
    [default_interface]
    runtimeclass ActorViewModel
    {
        ActorViewModel();       
        String Name;
        Windows.Foundation.Collections.IObservableVector<ActorComponent> Components{ get; };
    }
}

