#pragma once

namespace AuthoringTool
{
	[default_interface]
	runtimeclass ActorListViewModel
	{
		ActorListViewModel();		
		Windows.Foundation.Collections.IObservableMap<String, EngineInterface_WRC.ActorProxy> ActorInfos{ get; };
		Windows.Foundation.Collections.IObservableVector<EngineInterface_WRC.ActorProxy> TestList{ get; };
		String SelectedActorName;
	}
}

