#pragma once

import "ActorProperty.idl";
namespace AuthoringTool
{
    //declare actorcomponent's properties
    /*
    * 추후에 EngineCore에 프로퍼티만들면 빌드할때 스크립트 실행해서 파일을 떨구고 해당 파일 파싱해서 UI코드 빌드할떄 인클루드해서 빌드하도록 구조를 만들면 좋을듯.
    */

    runtimeclass TransformGroup : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {        
        Windows.Foundation.Numerics.Vector3 Position;
        Windows.Foundation.Numerics.Vector3 Rotation;
        Windows.Foundation.Numerics.Vector3 Scale;
    }

    runtimeclass Rendering : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        Boolean Visible;
    }

    runtimeclass StaticMeshProperties : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        Windows.Foundation.Collections.IObservableVector<String> StatcMeshTypes{ get; };
        String SelectedStaticMesh;
    }

    runtimeclass ActorComponent : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {                
        ActorComponent(String name);
        String Name{ get; };
                                
        Windows.Foundation.Collections.IObservableVector<ActorProperty> Properties{ get; };
        Windows.Foundation.Collections.IObservableVector<StaticMeshProperties> Properties{ get; };

    }
}