#include "pch.h"
#include "ActorListViewModel.h"
#include "ActorListViewModel.g.cpp"
//#include "ActorInfo.h"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.
//static_assert(false, "This file is generated by a tool and will be overwritten. Open this error and view the comment for assistance.");

namespace winrt::AuthoringTool::implementation
{
    ActorListViewModel::ActorListViewModel()
    {                
        //Proxy로부터 ActorListInfo를 받아서 이 vector를 업데이트 시킴
        //observableVector이기 떄문에 추가, 삭제시 알수있음.
        //속성은 람다로 연결시켜줘야 변화를 알수 있을듯.
    }
    winrt::Windows::Foundation::Collections::IObservableVector<winrt::EngineInterface_WRC::ActorProxy> ActorListViewModel::ActorInfos()
    {        
        return viewActorList_;
    }

    void ActorListViewModel::ActorInfos(const winrt::Windows::Foundation::Collections::IObservableVector<winrt::EngineInterface_WRC::ActorProxy>& actors)
    {
        viewActorList_ = actors;
    }

    winrt::hstring ActorListViewModel::SelectedActorName()
    {
        return hstring(L"test");
    }
    void ActorListViewModel::SelectedActorName(winrt::hstring const& value)
    {        
    }
    void ActorListViewModel::UpdateSceneActorInfo(const winrt::Windows::Foundation::Collections::IObservableVector<winrt::EngineInterface_WRC::ActorProxy>& actors)
    {
        viewActorList_ = actors;
    }
}
