#include "pch.h"
#include "TransformGroup.h"
#include "TransformGroup.g.cpp"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.
//static_assert(false, "This file is generated by a tool and will be overwritten. Open this error and view the comment for assistance.");

namespace winrt::AuthoringTool::implementation
{
    winrt::Windows::Foundation::Numerics::float3 TransformGroup::Position()
    {
        return position_;
    }
    void TransformGroup::Position(winrt::Windows::Foundation::Numerics::float3 const& value)
    {
        if (position_ != value)
        {
            position_ = value;
            propertyChanged_(*this, Microsoft::UI::Xaml::Data::PropertyChangedEventArgs{ L"Position" });
        }
    }
    winrt::Windows::Foundation::Numerics::float3 TransformGroup::Rotation()
    {
        return rotation_;
    }
    void TransformGroup::Rotation(winrt::Windows::Foundation::Numerics::float3 const& value)
    {
        if (rotation_ != value)
        {
            rotation_ = value;
            propertyChanged_(*this, Microsoft::UI::Xaml::Data::PropertyChangedEventArgs{ L"Rotation" });
        }
    }
    winrt::Windows::Foundation::Numerics::float3 TransformGroup::Scale()
    {
        return scale_;
    }
    void TransformGroup::Scale(winrt::Windows::Foundation::Numerics::float3 const& value)
    {
        if (scale_ != value)
        {
            scale_ = value;
            propertyChanged_(*this, Microsoft::UI::Xaml::Data::PropertyChangedEventArgs{ L"Scale" });
        }
    }
    winrt::event_token TransformGroup::PropertyChanged(winrt::Microsoft::UI::Xaml::Data::PropertyChangedEventHandler const& handler)
    {
        return propertyChanged_.add(handler);
    }
    void TransformGroup::PropertyChanged(winrt::event_token const& token) noexcept
    {
        propertyChanged_.remove(token);
    }
}
